### ISSUE TITLE
*** [Makefile:8: xlauncher] Error 1

### ISSUE THREAD

**Issue by flaketill** [vatriani/xlauncher#1]
ar@linux: ~/home/me/xlauncher (master)$  make

-pipe -fstack-protector -O5 -fdata-sections -ffunction-sections -Wl,--gc-sections --param=ssp-buffer-size=4 -fexcess-precision=fast -DDATE="\"`date +'%Y'`\"" string.o file.o output.o lists.o -lX11 -o xlauncher main.c
/tmp/ccDVU82m.o: En la función `main':
main.c:(.text.startup.main+0x415): referencia a `searchInList' sin definir
collect2: error: ld devolvió el estado de salida 1
make: *** [Makefile:8: xlauncher] Error 1

ar@linux: ~/home/me/xlauncher (master)$

**Comment by vatriani** [comment]
Thx for reporting this error.
Fixed in 586024a  master
